import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My First Next App",
  description: "Generated by shahab",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full h-auto mx-auto mt-6 mb-10">
          <Navbar />
        </div>

        <div className="w-full max-w-6xl mx-auto min-h-[calc(100vh-68px)] my-10 px-4 sm:px-6 lg:px-8">
          {children}
        </div>

        <div className="w-full mt-4">
          <Footer />
        </div>
      </body>
    </html>
  );
}
