import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My First Next App",
  description: "Generated by shahab",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="h-[8vh] max-w-6xl mx-auto">
      <Navbar></Navbar>
      </div>
        <div className="max-w-6xl mx-auto min-h-[calc(100vh-68px)] mt-10">
        {children}
        </div>

        <div>
                <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
